[general]

live_config_reload = true

[cursor]

blink_interval = 250
unfocused_hollow = false
thickness = 0.2
style = { blinking = "Always", shape = "Underline" }

[selection]

save_to_clipboard = true

[window]

decorations = "none"
dynamic_title = true
opacity = 0.5
dynamic_padding = true
padding = { x = 10, y = 10 }
dimensions = { columns = 105, lines = 30}

[colors.primary]

background = "#000000"
foreground = "#c1c1c1"

[colors.normal]

black    = "#000000"
red      = "#f97583"
green    = "#5c5c5c"
yellow   = "#ffab70"
blue     = "#79b8ff"
magenta  = "#b392f0"
cyan     = "#9e9e9e"
white    = "#ffffff"

[colors.bright]

black    = "#555555"
red      = "#f97583"
green    = "#5c5c5c"
yellow   = "#ffab70"
blue     = "#79b8ff"
magenta  = "#b392f0"
cyan     = "#9e9e9e"
white    = "#ffffff"

[font]

normal      = { family = "VGA", style = "Regular" }
bold        = { family = "VGA", style = "Bold" }
italic      = { family = "VGA", style = "Italic" }
bold_italic = { family = "VGA", style = "BoldItalic" }
size        = 10
